### PR TITLE
Fixed #144 typo

### LINKED ISSUE #144: Typo on homepage
On the homepage of our docs, we have a sentence that reads...

> Switches intelligently between native libraries to be work in both Node.js and browser environments.

The "to be work" phrase is a typo; it should just be "to work" instead.

### PR DESCRIPTION
**Pull request by Nam-Nguyen-Dev**
Closes #144

### CODE REVIEW

**Comment by WesCossick** [comment]
Hey @Nam-Nguyen-Dev, thanks for submitting this bug fix! So that the issue gets linked and automatically closed, can you mention that this PR closes #144 in the description? From [the contributing guide](https://github.com/sparksuite/w3c-css-validator/blob/master/CONTRIBUTING.md#9-open-a-pr):

> If your PR closes one or more issues, write `Closes #X` for each in the PR description (`X` being the issue number).

**Comment by WesCossick** [comment]
It also looks like the code needs formatting since the "Lint code" check above is failing. You can do that by running `yarn format` from the root of your forked repository!

**Comment by Nam-Nguyen-Dev** [comment]
Thanks for the feedback! Please let me know if there is anything else I need to fix.

**Comment by WesCossick** [comment]
Hey @Nam-Nguyen-Dev, not sure how our team missed your latest comment. The notification may not have come through our Slack channel.

Anyway, it looks like running `yarn format` made changes to nearly every file in the repository. You can see that in the "Files changed" tab. There don't appear to be any visible changes, so I suspect the newlines got changed somehow, but that shouldn't have happened just by running `yarn format`.

Linux machines default to using a single newline `\n` whereas Windows machines default to `\r\n`. Are you using Windows by chance? And if so, was running `yarn format` the only thing you did?

Hopefully we can figure out why this happened and prevent it from happening to others.

**Comment by Nam-Nguyen-Dev** [comment]
Hey Wes, I did originally try this on a Windows machine and ran into some issues with yarn format. After playing around with it, I must've messed something up.

I'm going to try and start all over and hopefully get it right this time. Thank you for taking the time and looking this over with me!

**Comment by WesCossick** [comment]
Sounds good! Also, we discovered why your earlier comment wasn't posted to our company's Slack channel: https://github.com/integrations/slack/issues/1500.

**Pull request closed without merging**
