### PR TITLE
Bad status code error

### LINKED ISSUE #98: Fails with large files
Not sure if this is a known issue, but thought I'd point it out. Because the text is passed through the query string, there's an upper bound on what you can validate, and I was running into it on some compiled stylesheets. Error would sometimes be a 400 bad request, sometimes an uncaught pipe error.

I got around this by just interacting with the webpage and parsing the html. It's brittle, and I only wanted errors, but could be a good starting point if anyone else needs to do this.

```js
// yarn add form-data node-fetch node-html-parser

async function validate(source) {
  // Reversed from interacting with https://jigsaw.w3.org/css-validator/#validate_by_input
  const form = new FormData();
  form.append("text", source);
  form.append("profile", "css3svg");
  form.append("usermedium", "all");
  form.append("type", "none");
  form.append("warning", "0");
  form.append("vextwarning", "");
  form.append("lang", "en");

  return fetch("https://jigsaw.w3.org/css-validator/validator", {
    headers: form.getHeaders(),
    body: form.getBuffer(),
    method: "POST",
  })
    .then((response) => {
      if (response.status !== 200) {
        throw new Error(`returned status code ${response.status}`);
      }
      return response.text();
    })
    .then((body) => {
      const root = HTMLParser.parse(body);
      const errors = root.querySelectorAll("tr.error").map((row) => {
        const line = parseInt(row.querySelector(".linenumber").text, 10);
        const error = row
          .querySelector(".parse-error")
          .text.replace(/\s+/g, " ")
          .trim();
        return { line, error };
      });
      return errors;
    });
}

### PR DESCRIPTION
**Pull request by corymharper**
In this pull request I added behavior to make sure we were throwing errors when a response had a bad status, and appended a message to some errors warning users of the package about trying to validate too much raw CSS.

Closes #98

### CODE REVIEW

**Comment by corymharper** [comment]
The behavior between node and the browser will not be exactly consistent... In Node environments I get a 400 status when I request so much raw text to be validated, however when using `fetch` in the browser it looks like the server isn't responding with an `Access-Control-Allow-Origin` header, and fetch is actually throwing a type error with a message similar to `Network request failed` so I'm just catching the error and appending a hint towards the possible cause in the browser, and I added a specific bad request error for when I get codes other than 200-300 in all other cases.

**Review by WesCossick — COMMENTED** [review]
> however when using fetch in the browser it looks like the server isn't responding with an Access-Control-Allow-Origin header

In this case, should we be calling the custom error class `BadStatusError` since it seems to encompass more than just bad statuses?

**Comment by corymharper** [comment]
> > however when using fetch in the browser it looks like the server isn't responding with an Access-Control-Allow-Origin header
> 
> In this case, should we be calling the custom error class `BadStatusError` since it seems to encompass more than just bad statuses?

I am not using that error class to handle that case, but rather just augmenting the type error message and throwing another type error.

**Comment by WesCossick** [comment]
Okay, I see, I missed that.

**Review by WesCossick — CHANGES_REQUESTED** [review]
This should reject any status code that isn't `2xx`. Right now it does, except for `300`, which it doesn't appear to throw an error for.

**Pull request merged**
